# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-11 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_Test_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
